# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CursoIOSAdvanced' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CursoIOSAdvanced
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'lottie-ios'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  pod 'Fabric'
  pod 'Crashlytics'
end
